# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  # python formatter
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of black
    hooks:
      - id: black
        language_version: python3  # Ensure it uses Python 3.x

  # rust formatter
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types: [rust]
